name: Deploy and Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build

    - name: dir
      run: |
        dir

    - name: Restore Packages
      run: nuget restore ClaimsWebApp/packages.config -PackagesDirectory D:\a\ClaimsWebApp\ClaimsWebApp\packages

    - name: Restore Packages OData
      run: nuget install Microsoft.Data.OData -Version 5.7.0.0 -OutputDirectory D:\a\ClaimsWebApp\ClaimsWebApp\packages

    - name: Restore Packages Owin 
      #run: nuget install Microsoft.Owin -Version 3.0.1.0 -OutputDirectory D:\a\ClaimsWebApp\ClaimsWebApp\packages
      run: nuget install Microsoft.Owin -Version 3.0.1.0 -OutputDirectory D:\a\ClaimsWebApp\ClaimsWebApp\packages


    - name: Build Solution
      run: |
        msbuild.exe AADGuide-CodeSamples.sln /target:ClaimsWebApp /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"

    - name: dir2
      run: |
        cd _build
        dir
        cd bin
        dir

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        #Add credentials like: http://chamindac.blogspot.com/2022/01/executing-azure-cli-commands-with.html

    - name: 'Run az commands'
      shell: pwsh
      run: |
        $Region="West Europe"
        $ResourceGroup="mftestweb"
        $WebResourceName="mftestweb"
        az group create -l $Region -n $ResourceGroup
        az appservice plan create -l $Region -g $ResourceGroup -n $WebResourceName  --is-linux --sku B1
        az webapp create -g $ResourceGroup -n $WebResourceName -p $WebResourceName